### PR TITLE
Informational page test updates

### PR DESCRIPTION
**Pull request by HobbyADD**
made recommended changes tot he InformationPges.test.ts and HomePage.ts files

from informaionpages.test.ts
removed unnecessary imports, urls and changed the test names to match their jira test script names and numbers 

in homepage.ts
removed unnecessary imports, created variables for xpaths and removed the explicit paths within the methods

### CODE REVIEW

**Review by jemnset — CHANGES_REQUESTED** [review]
InformationPage.test.ts comments
1. Pls check you import statements, you should really only need the HomePage file import
2. page.navigate() does not need to have the URL passed in. The HomePage constructor already does this
3. Pls name the tests with the test case ID and name from JIRA so we can track exactly which test cases these tests cover

HomePage.ts
1. Pls check the import statement, not sure what isThisTypeNode package is for?
2. All of the xPaths should be declared as class properties (like how you have done with requestApptLink for example), not hard coded into the getElement() method. Pls fix this for isContactPage(), isPatientGuidePage() and isCovidPage()

**Comment by HobbyADD** [comment]
uploaded updated files

**Review by ShaylaZimmerman — COMMENTED** [review]
I think the test file looks good. I like the use of comments. I do think it would be a nice addition under the describe section to change line 7 so that it reads const homePage= new HomePage(); .
From there you would need to update every instance of the word page to homePage.

**Review by jemnset — APPROVED** [review]
Looks good!

**Review by ShaylaZimmerman — APPROVED** [review]

**Pull request merged**
